/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'ccho' at '9/20/17 2:53 PM' with Gradle 2.14.1
 *
 * @author ccho, @date 9/20/17 2:53 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
